CREATE TABLE draw(
    id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    tournament varchar(64),
    round_num int,
    matchups varchar(200)
);

insert into draw(tournament, round_num, matchups) values('Wimbledon2019', 1, '[{"player1": "Roger Federer", "player2": "Rafael Nadal", "winner": "Roger Federer"}]');

insert into draw(tournament, round_num, matchups) values('Wimbledon2019', 2, '[{"player1": "Roger Federer", "player2": "Novak Djokovic", "winner": "Novak Djokovic"}]');