CREATE TABLE simple
(
    id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    field1 varchar(64),
    field2 varchar(64)
);

INSERT INTO simple (field1, field2) VALUES ('field1_value_delete', 'field2_value_delete');

INSERT INTO simple (field1, field2) VALUES ('field1_value_keep', 'field2_value_keep');